### PR TITLE
Add Video Capture Feature

### PR DESCRIPTION
**Pull request by lbegani**
Handle Mavlink command for Video Capture

### CODE REVIEW

**Comment by hamishwillee** [comment]
@lbegani So what is the docs impact of this? 

I think it requires:
1. UPdate to [overview](https://hamishwillee.gitbooks.io/camera-streaming-daemon/content/en/guide/overview.html) to say that MAVLink video capture is supported?
1. Addition of information about config file changes - addition of [vidcap](https://github.com/Dronecode/camera-streaming-daemon/pull/157/commits/91a4bad1eafe6c52f3cab3b57b92a9879185b8ae#diff-c603ddb75c825043d7f21b6f2f8b3a36R13)
   * Can you update the sample file?
   * I need to update https://hamishwillee.gitbooks.io/camera-streaming-daemon/content/en/guide/configuration_file.html with description of fields. Can you please explain them?

Is there anything else that needs to be captured? 

Does this now mean we have full MAVLink Camera Protocol support? I know we don't support publishing RTSP stream info through MAVLink yet, but not sure that is actually in the protocol (?)

**Comment by lbegani** [comment]
@hamishwillee 
I will update the sample config file with explanation which can be reference for your work

> Does this now mean we have full MAVLink Camera Protocol support? I know we don't support publishing RTSP stream info through MAVLink yet, but not sure that is actually in the protocol (?)

MAVLink message for video streaming is yet to be finalized . There is some work initiated now.  Other than that, I think CSD now handles all the mavlink messages related to camera.

**Comment by hamishwillee** [comment]
Thanks @lbegani 

In future, if you make changes that might affect docs can you create an issue in the docs repo explaining what might need to change. It is possible for me to miss this sort of thing, and in future I may not be around. Much easier to update the docs as part of making the changes than at some random point in the future :-)

**Comment by lbegani** [comment]
@hamishwillee 
Totally agree, I missed adding you as reviewer. But creating issue is a better solution to keep things in track, will be doing it in future.

> Can you let me know when the sample updates are done? 
I will update the issue once done

**Pull request merged**
